version: "3.8"

services:
  mysql:
    build: . # Usamos el Dockerfile del directorio actual
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=prueba
      - MYSQL_USER=squery
      - MYSQL_PASSWORD=12345
    ports:
      - "3306:3306" # Exponer el puerto 3306
    volumes:
      - mysql_data:/var/lib/mysql # Volumen para persistir los datos
    restart: unless-stopped # Reiniciar el contenedor si se detiene inesperadamente

# Definir un volumen persistente para los datos
volumes:
  mysql_data:
    driver: local
