version: "3.0"

services:
  mysql:
    image: diegomrza/mysql_db:latest # build: ./db
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/Script.sql:/docker-entrypoint-initdb.d/Script.sql # Script de inicialización
    restart: always

  # imggo:
  #   image: diegomrza/goservice:latest # build: ./backend    
  #   container_name: go-container
  #   ports:
  #     - "5200:5200"
  #   restart: always

  nodejs:
    image: diegomrza/nodejsapi:latest # build: ./api
    container_name: nodejs-container
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - mysql

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    ports:
      - "9090:9090"
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - nodejs

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    ports:
      - "3000:3000" # Exponer el puerto 3000
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin

    volumes:
      - grafana_data:/var/lib/grafana # Volumen para persistir los datos
    depends_on:
      - mysql

volumes:
  mysql_data:
  grafana_data:
